wandb_version: 1

model:
  desc: null
  value:
    input_dim: 5
    d_model: 64
    max_len: 1000
    num_heads: 8
    num_layers: 6
    ff_dim: 128
    dropout: 0.1
    activation: gelu
    layer_norm_eps: 1.0e-05
    batch_first: true
    bias: true
dataset:
  desc: null
  value:
    symbols_file: symbols.csv
    seq_len: 500
    dir: data
    period: 60d
    interval: 2m
    download: false
    columns:
    - Datetime
    - Open
    - High
    - Low
    - Close
    - Volume
optimizer:
  desc: null
  value:
    fn: adam
    lr: 0.001
    momentum: 0.9
    beta1: 0.9
    beta2: 0.999
criterion:
  desc: null
  value: mse_loss
wandb:
  desc: null
  value: true
compile:
  desc: null
  value:
    disable: true
    fullgraph: true
    dynamic: null
    backend: inductor
    mode: max-autotune
train:
  desc: null
  value:
    epochs: 30
    batch_size: 32
    num_workers: 4
    log_freq: 50
    model_dir: models
_wandb:
  desc: null
  value:
    python_version: 3.11.8
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712728402.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.11.8
      5: 0.16.4
      8:
      - 5
      13: linux-x86_64
